#!/bin/bash

set -e
set -x

npm run build

# we should make sure that package.json is committed
release_title="v$(cat package.json | jq -r .version)"

gh release create -n "what does this do" --title $release_title --prerelease $release_title dist/hny.js*
